server:
  port: 8080
  servlet:
    context-path: /library-book
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

spring:
  application:
    name: demo-book
  datasource:
    url: jdbc:h2:file:C:\Users\gauth\Desktop\db-data\book
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE