spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8888"
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh # allow config server to send refresh data request to client using this data

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
