server:
  port: 8085
  servlet:
    context-path: /web-gateway
spring:
  application:
    name: web-gateway
  kafka:
    producer:
      bootstrap-servers:
        - localhost:29092
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

