spring:
  application:
    name: inventory-service
  config:
    import: "configserver:http://localhost:8888"
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh # allow config server to send refresh data request to client using this data - fixme: should use queue
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

business:
  supplierName: firstSupplier